# Generated by Django 4.1 on 2022-08-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='next_action',
            new_name='NextAction',
        ),
    ]
