# Generated by Django 4.1 on 2022-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_alter_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='TG',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='VK',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='nextaction',
            name='action_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
